import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyApp from "./myapp";
import { RecoilProvider } from "./recoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full"}>
        <RecoilProvider>
          <MyApp>{children}</MyApp>
        </RecoilProvider>
      </body>
    </html>
  );
}
